packer {
  required_plugins {
    googlecompute = {
      source  = "github.com/hashicorp/googlecompute"
      version = "~> 1"
    }
  }
}
variable "credentials" {}
variable "project_id" {}
variable "DB_PASSWORD" {}

source "googlecompute" "autogenerated_1" {
  credentials_file  = var.credentials
  image_description = "Custom image with application and MySQL"
  image_labels = {
    built_by = "packer"
    version  = ">=0_0_1"
  }
  image_name          = "csye-centos8"
  network             = "default"
  project_id          = var.project_id
  source_image        = "centos-stream-8-v20240110"
  source_image_family = "centos-8-stream"
  ssh_username        = "packer"
  zone                = "us-east1-d"
}

build {
  sources = ["source.googlecompute.autogenerated_1"]

  provisioner "shell" {
    inline = [
      "sudo setenforce 0"
    ]
  }


  // provisioner "file" {
  //   source      = "./install_mysql.sh"
  //   destination = "/tmp/install_mysql.sh"
  // }

  // provisioner "file" {
  //   source      = "./install_nodejs.sh"
  //   destination = "/tmp/install_nodejs.sh"
  // }

  provisioner "file" {
    source      = "/home/runner/work/webapp/webapp/webapp-fork/api/webapp.zip"
    destination = "/tmp/webapp.zip"
  }
  // provisioner "file"{
  //   source      = "./permission.sh"
  //   destination = "/tmp/permission.sh"
  // }

  provisioner "shell" {
    scripts = ["./install_nodejs.sh", "./install_mysql.sh", "./permission.sh", "./installations.sh"]
    environment_vars = [
      "DB_PASSWORD=${var.DB_PASSWORD}"
    ]
  }

}
