packer {
  required_plugins {
    googlecompute = {
      source  = "github.com/hashicorp/googlecompute"
      version = "=> 1"
    }
  }
}

source "googlecompute" "autogenerated_1" {
  credentials_file  = "csye-6225-414700-23f67299b684.json"
  image_description = "Custom image with application and MySQL"
  image_labels = {
    built_by = "packer"
    version  = "0_0_1"
  }
  image_name          = "csye-centos8"
  network             = "default"
  project_id          = "csye-6225-414700"
  source_image        = "centos-stream-8-v20240110"
  source_image_family = "centos-8-stream"
  ssh_username        = "dev"
  zone                = "us-east1-b"
}

build {
  sources = ["source.googlecompute.autogenerated_1"]

  provisioner "shell" {
    script = "install_mysql.sh"
  }

  provisioner "shell" {
    script = "install_nodejs.sh"
  }

}
