packer {
  required_plugins {
    googlecompute = {
      source  = "github.com/hashicorp/googlecompute"
      version = "~> 1"
    }
  }
}
variable "credentials" {}
variable "project_id" {}
variable "MYSQL_PASSWORD" {}

source "googlecompute" "autogenerated_1" {
  credentials_file  = var.credentials
  image_description = "Custom image with application and MySQL"
  image_labels = {
    built_by = "packer"
    version  = ">=0_0_1"
  }
  image_name          = "csye-centos8"
  network             = "default"
  project_id          = "csye-6225-terraform-415001"
  source_image        = "centos-stream-8-v20240110"
  source_image_family = "centos-8-stream"
  ssh_username        = "dev"
  zone                = "us-east1-b"
}

build {
  sources = ["source.googlecompute.autogenerated_1"]
  
  provisioner "shell" {
    inline = [
      "sudo setenforce 0"
    ]
  }


  provisioner "file" {
    source      = "./install_mysql.sh"
    destination = "/tmp/install_mysql.sh"
  }

  provisioner "file" {
    source      = "./install_nodejs.sh"
    destination = "/tmp/install_nodejs.sh"
  }

  provisioner "file"{
    source = "/home/runner/work/webapp/webapp/webapp-fork.zip"
    destination = "/tmp/webapp.zip"
  }
  provisioner "file"{
    source      = "./permissions.sh"
    destination = "/tmp/permissions.sh"
  }

  provisioner "shell" {
    scripts = ["./install_mysql.sh", "./install_nodejs.sh", "./permission.sh", "./installations.sh"]
    environment_vars = [
      "MYSQL_PASSWORD=${var.MYSQL_PASSWORD}"
    ]
  }

}
