name: Node.js CI with MySQL

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install MySQL
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-server
          sudo systemctl start mysql
          sudo mysql -e "CREATE DATABASE IF NOT EXISTS Health;" -uroot

      - name: Run tests
        run: npm test
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          PORT: ${{ secrets.PORT }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_DATABASE: ${{ secrets.DB_DATABASE}}

      - name: Delete database
        run: |
          mysql -u${{ secrets.DB_USERNAME}}
                -p${{ secrets.DB_PASSWORD}}
                -e "DROP DATABASE ${{ secrets.DB_DATABASE}};" || exit 1
