name: mysql

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: mysql
    runs-on: ubuntu-latest

    # This keyword is used to define the build strategy for your workflow. In this case, it's specifying a matrix strategy
    strategy:
      # This sub-keyword defines a matrix build strategy, which allows you to run your job in multiple configurations
      matrix:
        # This sub-keyword defines the Node.js version to use for the job
        node-version: [18.x]

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Use ${{matrix.node-version}} to setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
            cd assignment02
            npm install

      - name: Install MySQL
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-server

      - name: Set up MySQL
        run: |
          sudo systemctl start mysql
          mysql -uroot  -proot -e "CREATE DATABASE IF NOT EXISTS Health;" || exit 1
          mysql -uroot  -proot -e "USE Health;" || exit 1

      - name: Run tests
        env:
          MYSQL_HOSTNAME: ${{secrets.MYSQL_HOSTNAME}}
          MYSQL_PASSWORD: root
          MYSQL_DATABASENAME: ${{secrets.MYSQL_DATABASENAME}}
          MYSQL_USERNAME: root
          SALT_ROUNDS: ${{secrets.SALT_ROUNDS}}
          PORT: ${{secrets.PORT}}
        run: |
            cd assignment02
            npm run test

      - name: Delete Database
        run: |
          mysql -uroot  -proot -e "DROP DATABASE Health;" || exit 1