name: Packer CI
on:
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  packer-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Packer
        run: |
          curl -o packer.zip https://releases.hashicorp.com/packer/1.7.2/packer_1.7.2_linux_amd64.zip
          unzip packer.zip
          sudo mv packer /usr/local/bin/

      - name: initialize  packer
        run: |
          cd webapp-fork/api/packer
          packer init packer.pkr.hcl

      - name: Run packer fmt
        run: |
          cd webapp-fork/api/packer
          packer fmt -check packer.pkr.hcl
          if [ $? -ne 0 ]; then
            echo "packer fmt has made changes to the packer template. Please run 'packer fmt' locally and commit the changes."
            exit 1
          fi

      - name: Run packer validate
        run: |
          FILE="webapp-fork/api/packer/packer.pkr.hcl"
          cd webapp-fork/api/packer
          packer validate -var "project_id=${{secrets.GCP_PROJECT_ID}}" -var "credentials=$GOOGLE_APP_CREDENTIALS" -var "DB_PASSWORD=${{secrets.DB_PASSWORD}}" -var "DB_USERNAME=${{secrets.DB_USERNAME}}" -var "DB_DATABASE=${{secrets.DB_DATABASE}}" -var "PORT=${{secrets.PORT}}" -var "DB_HOST=${{secrets.DB_HOST}}" $FILE || exit 1
          if [ $? -ne 0 ]; then
            echo "packer validate failed to validate the packer template. Please fix the template."
            exit 1
          fi
