name: Packer-Validate CI

on:
  pull_request:
    #types: [closed]
    branches:
      - main
  workflow_dispatch:

jobs:
  packer-checks:
    #if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up MySQL
        run: |
          sudo systemctl start mysql
          mysql -u${{secrets.DB_USERNAME}}  -p${{secrets.DB_PASSWORD}} -e "CREATE DATABASE IF NOT EXISTS ${{ secrets.DB_DATABASE }};" || exit 1
          mysql -u${{secrets.DB_USERNAME}}  -p${{secrets.DB_PASSWORD}} -e "USE ${{ secrets.DB_DATABASE }};" || exit 1

      - name: Install Nodejs dependencies
        run: |
          cd webapp-fork/api
          npm install

      - name: Run Nodejs tests
        env:
          MYSQL_HOSTNAME: ${{secrets.DB_HOST}}
          MYSQL_PASSWORD: ${{secrets.DB_PASSWORD}}
          MYSQL_DATABASENAME: ${{secrets.DB_DATABASE}}
          MYSQL_USERNAME: ${{secrets.DB_USERNAME}}
          PORT: ${{secrets.PORT}}
        run: |
          cd webapp-fork/api
          npm run test

      - name: Zip Node.js application
        run: |
          cd webapp-fork/api
          npm run zip

      - name: Unzip Nodejs application
        run: |
          sudo unzip webapp-fork/api/webapp-fork.zip -d /home

      - name: Install Packer
        run: |
          curl -o packer.zip https://releases.hashicorp.com/packer/1.7.2/packer_1.7.2_linux_amd64.zip
          unzip packer.zip
          sudo mv packer /usr/local/bin/

      - name: initialize  packer
        run: |
          cd webapp-fork/api/packer
          packer init .

      - name: Build Packer image
        run: |
          cd webapp-fork/api/packer
          packer build -var "project_id=csye-6225-terraform-415001" -var "credentials=credential.json" .\setup.pkr.hcl
