name: Packer-Validate CI

on:
  pull_request:
    branches:
      - main

jobs:
  packer-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Zip Node.js application
        run: |
          npm run zip

      - name: Install Packer
        run: |
          curl -o packer.zip https://releases.hashicorp.com/packer/1.7.2/packer_1.7.2_linux_amd64.zip
          unzip packer.zip
          sudo mv packer /usr/local/bin/

      - name: initialize  packer
        run: |
          cd webapp-fork/api/packer
          packer init packer.json.pkr.hcl

      - name: Build Packer image
        run: |
          packer build packer.json.pkr.hcl
